# document: "{{document}}"
icl_document: "{{icl_document}}"
document_outline: "{{document_outline}}"
icl_query_1: "{{icl_query_1}}"
icl_response_1: "{{icl_response_1}}"
icl_query_2: "{{icl_query_2}}"
icl_response_2: "{{icl_response_2}}"
icl_query_3: "{{icl_query_3}}"
icl_response_3: "{{icl_response_3}}"
icl_query_4: "{{icl_query_4}}"
icl_response_4: "{{icl_response_4}}"
icl_query_5: "{{icl_query_5}}"
icl_response_5: "{{icl_response_5}}"
# leaf_node_path: "{{leaf_node_path}}"